In [ ]:
from google.colab import files

uploaded = files.upload()

Saving exams.csv to exams (2).csv

In [ ]:
import sys
import pandas as pd
import numpy as np
import sklearn
import matplotlib
import seaborn as sns

print("Library Versions")
print("-" * 40)
print(f"Pandas         : {pd.__version__}")
print(f"NumPy          : {np.__version__}")
print(f"Scikit-learn   : {sklearn.__version__}")
print(f"Matplotlib     : {matplotlib.__version__}")
print(f"Seaborn        : {sns.__version__}")

Library Versions
----------------------------------------
Pandas         : 2.2.2
NumPy          : 2.0.2
Scikit-learn   : 1.6.1
Matplotlib     : 3.10.0
Seaborn        : 0.13.2

In [ ]:
import pandas as pd
import seaborn as sns

In [ ]:
df = pd.read_csv("exams.csv")
print(df)

     gender race/ethnicity parental level of education         lunch  \
0    female        group D                some college      standard
1      male        group D          associate's degree      standard
2    female        group D                some college  free/reduced
3      male        group B                some college  free/reduced
4    female        group D          associate's degree      standard
..      ...            ...                         ...           ...
995    male        group C                some college      standard
996    male        group C                some college      standard
997  female        group A                 high school      standard
998    male        group E                 high school      standard
999    male        group D                 high school      standard

    test preparation course  math score  reading score  writing score
0                 completed          59             70             78
1                      none          96             93             87
2                      none          57             76             77
3                      none          70             70             63
4                      none          83             85             86
..                      ...         ...            ...            ...
995                    none          77             77             71
996                    none          80             66             66
997               completed          67             86             86
998                    none          80             72             62
999                    none          58             47             45

[1000 rows x 8 columns]

In [ ]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group D,some college,standard,completed,59,70,78
1,male,group D,associate's degree,standard,none,96,93,87
2,female,group D,some college,free/reduced,none,57,76,77
3,male,group B,some college,free/reduced,none,70,70,63
4,female,group D,associate's degree,standard,none,83,85,86

In [ ]:
print(df.head(10))

   gender race/ethnicity parental level of education         lunch  \
0  female        group D                some college      standard
1    male        group D          associate's degree      standard
2  female        group D                some college  free/reduced
3    male        group B                some college  free/reduced
4  female        group D          associate's degree      standard
5    male        group C            some high school      standard
6  female        group E          associate's degree      standard
7  female        group B            some high school      standard
8    male        group C            some high school      standard
9  female        group C           bachelor's degree      standard

  test preparation course  math score  reading score  writing score
0               completed          59             70             78
1                    none          96             93             87
2                    none          57             76             77
3                    none          70             70             63
4                    none          83             85             86
5                    none          68             57             54
6                    none          82             83             80
7                    none          46             61             58
8                    none          80             75             73
9               completed          57             69             77

In [ ]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,male,group C,some college,standard,none,77,77,71
996,male,group C,some college,standard,none,80,66,66
997,female,group A,high school,standard,completed,67,86,86
998,male,group E,high school,standard,none,80,72,62
999,male,group D,high school,standard,none,58,47,45

In [ ]:
df.tail(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,female,group C,some high school,standard,none,70,77,76
991,female,group A,associate's degree,standard,none,72,77,77
992,male,group A,associate's degree,free/reduced,completed,75,67,67
993,male,group D,some high school,standard,none,83,74,80
994,female,group B,associate's degree,standard,none,82,97,90
995,male,group C,some college,standard,none,77,77,71
996,male,group C,some college,standard,none,80,66,66
997,female,group A,high school,standard,completed,67,86,86
998,male,group E,high school,standard,none,80,72,62
999,male,group D,high school,standard,none,58,47,45

In [ ]:
print(df.shape)

(1000, 8)

In [ ]:
rows, columns = df.shape
print(f"Rows = {rows}")
print(f"Columns = {columns}")

Rows = 1000
Columns = 8

In [ ]:
df['assignments_completed']

KeyError: 'assignments_completed'